//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FebraSoft.Infraestrutura.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FebraSoftDBEntities : DbContext
    {
        public FebraSoftDBEntities()
            : base("name=FebraSoftDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<NFe> NFes { get; set; }
        public virtual DbSet<NFeItem> NFeItens { get; set; }
        public virtual DbSet<Produto> Produtos { get; set; }
        public virtual DbSet<NFeRecebida> NfesRecebidas { get; set; }
        public virtual DbSet<NFeRecebidaItem> NFesRecebidasItens { get; set; }
    }
}
