//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FebraSoft.Infraestrutura.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class NFeRecebidaItem
    {
        public int numeroNfeRecebida { get; set; }
        public int numeroItem { get; set; }
        public int codProduto { get; set; }
        public int cfop { get; set; }
        public int numeroLote { get; set; }
        public decimal quantidade { get; set; }
        public decimal valor { get; set; }
        public decimal percentualICMS { get; set; }
        public decimal percentualIPI { get; set; }
        public decimal valorICMS { get; set; }
        public decimal valorIPI { get; set; }
    
        public virtual Produto Produto { get; set; }
    }
}
